config/routes.rb
Rails.application.routes.draw do

  resources :benefits
  resources :pages
  resources :products
  devise_for :users

  root to: "pages#home"

  get 'terms', to: 'pages#terms', as: 'terms'

  get 'languages', to: 'pages#languages', as: 'languages'
  get 'countries', to: 'pages#countries', as: 'countries'
  get 'language/:language', to: 'products#language', as: 'language'
  get 'country/:country', to: 'products#country', as: 'country'

  get ':country/:url', to: 'products#view', as: 'view_product'  

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/benefit.rb
class Benefit < ApplicationRecord
  belongs_to :page

  has_one_attached :image
end

app/controllers/benefits_controller.rb
class BenefitsController < ApplicationController
  before_action :set_benefit, only: [:show, :edit, :update, :destroy]
  before_action :require_admin

  # GET /benefits
  # GET /benefits.json
  def index
    @benefits = Benefit.all
  end

  # GET /benefits/1
  # GET /benefits/1.json
  def show
  end

  # GET /benefits/new
  def new
    @benefit = Benefit.new
  end

  # GET /benefits/1/edit
  def edit
  end

  # POST /benefits
  # POST /benefits.json
  def create
    @benefit = Benefit.new(benefit_params)

    respond_to do |format|
      if @benefit.save
        format.html { redirect_to @benefit, notice: 'Benefit was successfully created.' }
        format.json { render :show, status: :created, location: @benefit }
      else
        format.html { render :new }
        format.json { render json: @benefit.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /benefits/1
  # PATCH/PUT /benefits/1.json
  def update
    respond_to do |format|
      if @benefit.update(benefit_params)
        format.html { redirect_to @benefit, notice: 'Benefit was successfully updated.' }
        format.json { render :show, status: :ok, location: @benefit }
      else
        format.html { render :edit }
        format.json { render json: @benefit.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /benefits/1
  # DELETE /benefits/1.json
  def destroy
    @benefit.destroy
    respond_to do |format|
      format.html { redirect_to benefits_url, notice: 'Benefit was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_benefit
      @benefit = Benefit.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def benefit_params
      params.require(:benefit).permit(:page_id, :image, :bold, :information, :language)
    end
end

app/helpers/benefits_helper.rb
module BenefitsHelper
end

app/views/benefits/_form.html.erb
<br><br><br><br>
<%= form_with(model: benefit, local: true) do |form| %>
  <% if benefit.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(benefit.errors.count, "error") %> prohibited this benefit from being saved:</h2>

      <ul>
        <% benefit.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :page_id %>
    <%= form.text_field :page_id %>
  </div>

  <div class="field">
    <%= form.label :image %>
    <%= form.file_field :image %>
  </div>

  <div class="field">
    <%= form.label :bold %>
    <%= form.text_field :bold %>
  </div>

  <div class="field">
    <%= form.label :information %>
    <%= form.text_field :information %>
  </div>

  <div class="field">
    <%= form.label :language %>
    <%= form.text_field :language %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/benefits/edit.html.erb
<h1>Editing Benefit</h1>

<%= render 'form', benefit: @benefit %>

<%= link_to 'Show', @benefit %> |
<%= link_to 'Back', benefits_path %>

app/views/benefits/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Benefits</h1>

<table>
  <thead>
    <tr>
      <th>Page</th>
      <th>Image</th>
      <th>Bold</th>
      <th>Information</th>
      <th>Language</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @benefits.each do |benefit| %>
      <tr>
        <td><%= benefit.page_id %></td>
        <td><%= benefit.image %></td>
        <td><%= benefit.bold %></td>
        <td><%= benefit.information %></td>
        <td><%= benefit.language %></td>
        <td><%= link_to 'Show', benefit %></td>
        <td><%= link_to 'Edit', edit_benefit_path(benefit) %></td>
        <td><%= link_to 'Destroy', benefit, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Benefit', new_benefit_path %>

app/views/benefits/new.html.erb
<h1>New Benefit</h1>

<%= render 'form', benefit: @benefit %>

<%= link_to 'Back', benefits_path %>

app/views/benefits/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Page:</strong>
  <%= @benefit.page_id %>
</p>

<p>
  <strong>Image:</strong>
  <%= @benefit.image %>
</p>

<p>
  <strong>Bold:</strong>
  <%= @benefit.bold %>
</p>

<p>
  <strong>Information:</strong>
  <%= @benefit.information %>
</p>

<p>
  <strong>Language:</strong>
  <%= @benefit.language %>
</p>

<%= link_to 'Edit', edit_benefit_path(@benefit) %> |
<%= link_to 'Back', benefits_path %>