config/routes.rb
Rails.application.routes.draw do

  resources :benefits
  resources :pages
  resources :products
  devise_for :users

  root to: "pages#home"

  get 'terms', to: 'pages#terms', as: 'terms'

  get 'languages', to: 'pages#languages', as: 'languages'
  get 'countries', to: 'pages#countries', as: 'countries'
  get 'language/:language', to: 'products#language', as: 'language'
  get 'country/:country', to: 'products#country', as: 'country'

  get ':country/:url', to: 'products#view', as: 'view_product'  

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/views/pages/_form.html.erb
<%= form_with(model: page, local: true) do |form| %>
  <% if page.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(page.errors.count, "error") %> prohibited this page from being saved:</h2>

      <ul>
        <% page.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :lead %>
    <%= form.text_field :lead %>
  </div>

  <div class="field">
    <%= form.label :subtitle %>
    <%= form.text_field :subtitle %>
  </div>

  <div class="field">
    <%= form.label :cta_text %>
    <%= form.text_field :cta_text %>
  </div>

  <div class="field">
    <%= form.label :sub_cta %>
    <%= form.text_field :sub_cta %>
  </div>

  <div class="field">
    <%= form.label :terms %>
    <%= form.text_field :terms %>
  </div>

  <div class="field">
    <%= form.label :benefits_header %>
    <%= form.text_field :benefits_header %>
  </div>

  <div class="field">
    <%= form.label :product_name %>
    <%= form.text_field :product_name %>
  </div>

  <div class="field">
    <%= form.label :product_price %>
    <%= form.text_field :product_price %>
  </div>

  <div class="field">
    <%= form.label :product_frequency %>
    <%= form.text_field :product_frequency %>
  </div>

  <div class="field">
    <%= form.label :product_info %>
    <%= form.text_field :product_info %>
  </div>

  <div class="field">
    <%= form.label :product_features %>
    <%= form.text_area :product_features %>
  </div>

  <div class="field">
    <%= form.label :product_cta %>
    <%= form.text_field :product_cta %>
  </div>

  <div class="field">
    <%= form.label :language %>
    <%= form.text_field :language %>
  </div>

  <div class="field">
    <%= form.label :product_id %>
    <%= form.text_field :product_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/pages/countries.html.erb
<style>
  body {
    background-color: #000;
  }
  #select {
    min-height: 100vh;
    background-color: #fff;
  }
</style>

<div class="h-20">

</div>

<div id="select" class="text-left">
  <div class="flex mb-4">
    <div id="hero" class="w-full min-h-64 pt-40 md:pt-32 px-5 md:px-16 bg-no-repeat bg-contain bg-right-bottom">
      <h1 id="lead" class="text-5xl font-semibold ">Select your country:</h1><br>
      <a href="/country/uk/" class="market pull-left" rel="uk" title="United Kingdom">
        <span class="media-object flag-icon flag-icon-uk"></span>
        United Kingdom
      </a>
      <br><br>
      <a href="/country/ro/" class="market pull-left" rel="ro" title="Romania">
        <span class="media-object flag-icon flag-icon-ro"></span>
        România
      </a>      
    </div>
  </div>
  <br><br>
</div>

app/views/pages/edit.html.erb
<h1>Editing Page</h1>

<%= render 'form', page: @page %>

<%= link_to 'Show', @page %> |
<%= link_to 'Back', pages_path %>

app/views/pages/home.html.erb
<style>
  .hero_cta {
    background-color: #fff;
    color: #000; 
    transition: all; 
    display: inline-block;
  }
  .hero_cta:hover {
    transform: scale(1.05);
  }  

  #lead {
    font-size: 3rem;
  }

  .sub2 {
    font-size: 1rem;
  }

  @media (min-width: 768px) {
    #lead {
      font-size: 4rem;
    }

    .sub2 {
      font-size: 1.125rem;
    }    
  }
</style>

<div class="index-homepage text-center md:pt-32">
  <div class="flex flex-wrap mb-4">
    <div id="hero" class="w-full min-h-64 pt-40 md:pt-32 px-5 md:px-16 bg-no-repeat bg-contain bg-right-bottom">
      <h1 id="lead" class="font-semibold ">My Spotify Exercise.</h1><br>
      <h2 class="sub2" class="font-medium">Steve Farnworth, Digital Content Builder 😉</h2>
      <a class="hero_cta w-full md:w-auto text-center tracking-widest font-medium uppercase py-2 px-4 rounded-full px-12 py-3 my-10" href="/uk/premium">
        UK Premium Page
      </a>
      <br><br>
      <div class="flex flex-wrap mt-12">
        <div class="w-full md:w-1/4 flex flex-wrap md:justify-center text-left md:text-center mb-10">
          <div class="w-2/5 md:w-full md:pb-5 text-left md:text-center font-semibold">
            <span class="text-5xl"><%= icon('fas', 'file-alt') %></span>
          </div>
          <div class="w-3/5 md:w-full">
            <span class="font-semibold text-xl">Multiple pages.</span><br>
            All styled against existing Spotify pages, colours and imagery.
            <br><br>
          </div>
        </div>
        <br>
        <div class="w-full md:w-1/4 flex flex-wrap md:justify-center text-left md:text-center mb-10">
          <div class="w-2/5 md:w-full md:pb-5 text-left md:text-center font-semibold">
            <span class="text-5xl"><%= icon('fas', 'code') %></span>
          </div>
          <div class="w-3/5 md:w-full">
            <span class="font-semibold text-xl">Custom CMS.</span><br>
            Built from scratch in Ruby on Rails, but easily possible in any off the shelf CMS.
            <br><br>
          </div>
        </div>
        <br>
        <div class="w-full md:w-1/4 flex flex-wrap md:justify-center text-left md:text-center mb-10">
          <div class="w-2/5 md:w-full md:pb-5 text-left md:text-center font-semibold">
            <span class="text-5xl"><%= icon('fas', 'language') %></span>
          </div>
          <div class="w-3/5 md:w-full">
            <span class="font-semibold text-xl">Language and Country choice.</span><br>
            Separate selections for language and country. 2 languages live.
            <br><br>
          </div>
        </div>
        <br>
        <div class="w-full md:w-1/4 flex flex-wrap md:justify-center text-left md:text-center mb-10">
          <div class="w-2/5 md:w-full md:pb-5 text-left md:text-center font-semibold">
            <span class="text-5xl"><%= icon('fas', 'mobile-alt') %></span>
          </div>
          <div class="w-3/5 md:w-full">
            <span class="font-semibold text-xl">Responsive.</span><br>
            Works on mobile and desktop - a few more things to tweak, but close.
            <br><br>
          </div>
        </div>
        <br>   
      </div>               


    </div>
  </div>
  <br><br>
</div>

app/views/pages/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Pages</h1>

<table>
  <thead>
    <tr>
      <th>Lead</th>
      <th>Subtitle</th>
      <th>Cta text</th>
      <th>Sub cta</th>
      <th>Terms</th>
      <th>Benefits header</th>
      <th>Product name</th>
      <th>Product price</th>
      <th>Product frequency</th>
      <th>Product info</th>
      <th>Product features</th>
      <th>Product cta</th>
      <th>Language</th>
      <th>Product</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @pages.each do |page| %>
      <tr>
        <td><%= page.lead %></td>
        <td><%= page.subtitle %></td>
        <td><%= page.cta_text %></td>
        <td><%= page.sub_cta %></td>
        <td><%= page.terms %></td>
        <td><%= page.benefits_header %></td>
        <td><%= page.product_name %></td>
        <td><%= page.product_price %></td>
        <td><%= page.product_frequency %></td>
        <td><%= page.product_info %></td>
        <td><%= page.product_features %></td>
        <td><%= page.product_cta %></td>
        <td><%= page.language %></td>
        <td><%= page.product_id %></td>
        <td><%= link_to 'Show', page %></td>
        <td><%= link_to 'Edit', edit_page_path(page) %></td>
        <td><%= link_to 'Destroy', page, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Page', new_page_path %>

app/views/pages/languages.html.erb
<style>
  body {
    background-color: #000;
  }
  #select {
    min-height: 100vh;
    background-color: #fff;
  }
</style>

<div class="h-20">

</div>

<div id="select" class="text-left">
  <div class="flex mb-4">
    <div id="hero" class="w-full min-h-64 pt-40 md:pt-32 px-5 md:px-16 bg-no-repeat bg-contain bg-right-bottom">
      <h1 id="lead" class="text-5xl font-semibold ">Select your language:</h1><br>
      <a href="/language/en/" class="market pull-left" rel="en" title="English">
        English
      </a>
      <br><br>
      <a href="/language/ro/" class="market pull-left" rel="ro" title="Romanian">
        Română
      </a>      
    </div>
  </div>
  <br><br>
</div>

app/views/pages/new.html.erb
<h1>New Page</h1>

<%= render 'form', page: @page %>

<%= link_to 'Back', pages_path %>

app/views/pages/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Lead:</strong>
  <%= @page.lead %>
</p>

<p>
  <strong>Subtitle:</strong>
  <%= @page.subtitle %>
</p>

<p>
  <strong>Cta text:</strong>
  <%= @page.cta_text %>
</p>

<p>
  <strong>Sub cta:</strong>
  <%= @page.sub_cta %>
</p>

<p>
  <strong>Terms:</strong>
  <%= @page.terms %>
</p>

<p>
  <strong>Benefits header:</strong>
  <%= @page.benefits_header %>
</p>

<p>
  <strong>Product name:</strong>
  <%= @page.product_name %>
</p>

<p>
  <strong>Product price:</strong>
  <%= @page.product_price %>
</p>

<p>
  <strong>Product frequency:</strong>
  <%= @page.product_frequency %>
</p>

<p>
  <strong>Product info:</strong>
  <%= @page.product_info %>
</p>

<p>
  <strong>Product features:</strong>
  <%= @page.product_features %>
</p>

<p>
  <strong>Product cta:</strong>
  <%= @page.product_cta %>
</p>

<p>
  <strong>Language:</strong>
  <%= @page.language %>
</p>

<p>
  <strong>Product:</strong>
  <%= @page.product_id %>
</p>

<%= link_to 'Edit', edit_page_path(@page) %> |
<%= link_to 'Back', pages_path %>

app/views/pages/terms.html.erb
<style>
  body {
    background-color: #000;
  }
  #select {
    min-height: 100vh;
    background-color: #fff;
  }
</style>

<div class="h-20">

</div>

<div id="select" class="text-left">
  <div class="flex mb-4">
    <div id="hero" class="w-full min-h-64 pt-40 md:pt-32 px-5 md:px-16 bg-no-repeat bg-contain bg-right-bottom">
      <h1 id="lead" class="text-5xl font-semibold ">Terms & Conditions</h1><br>
      Some terms and conditions     
    </div>
  </div>
  <br><br>
</div>