config/routes.rb
Rails.application.routes.draw do

  resources :benefits
  resources :pages
  resources :products
  devise_for :users

  root to: "pages#home"

  get 'terms', to: 'pages#terms', as: 'terms'

  get 'languages', to: 'pages#languages', as: 'languages'
  get 'countries', to: 'pages#countries', as: 'countries'
  get 'language/:language', to: 'products#language', as: 'language'
  get 'country/:country', to: 'products#country', as: 'country'

  get ':country/:url', to: 'products#view', as: 'view_product'  

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/product.rb
class Product < ApplicationRecord
  has_many :pages

  has_one_attached :header_image
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:show, :edit, :update, :destroy]
  before_action :require_admin, except: [:view, :index, :language]

  # GET /products
  # GET /products.json
  def index
    @products = Product.all
  end

  def language
    cookies[:language] = { value: params[:language], expires: 1.year.from_now, domain: :all, path: "/" }
    redirect_to cookies[:last_page]
    flash[:notice] = "Language settings updated!"    
  end

  def country
    cookies[:country] = { value: params[:country], expires: 1.year.from_now, domain: :all, path: "/" }
    redirect_to cookies[:last_page]
    flash[:notice] = "Country settings updated!"    
  end  

  def view
    @product = Product.where("country = ? AND url = ?", params[:country], params[:url]).last
    @language = cookies[:language] || "en" 
    @page = @product.pages.where("language = ?", @language).last
    @features = @page.product_features.split("//")

    cookies[:last_page] = { value: "/#{params[:country]}/#{params[:url]}", expires: 1.year.from_now, domain: :all, path: "/" }
  end

  # GET /products/1
  # GET /products/1.json
  def show
  end

  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
  end

  # POST /products
  # POST /products.json
  def create
    @product = Product.new(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: 'Product was successfully created.' }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to @product, notice: 'Product was successfully updated.' }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url, notice: 'Product was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_product
      @product = Product.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_params
      params.require(:product).permit(:url, :header_color, :header_text_color, :header_image, :header_cta_colour, :header_cta_text_color, :country, :currency, :name)
    end
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/_benefits.html.erb
<div class="w-full md:w-1/4 flex flex-wrap md:justify-center text-left md:text-center mb-10">
  <div class="w-2/5 md:w-full md:pb-5">
    <center><%= image_tag benefits.image, style: "width: 50%;" %></center>
  </div>
  <div class="w-3/5 md:w-full">
    <span class="font-semibold text-xl"><%= benefits.bold %></span><br>
    <%= benefits.information %>
    <br><br>
  </div>
</div>
<br>

app/views/products/_form.html.erb
<%= form_with(model: product, local: true) do |form| %>
  <% if product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
        <% product.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :url %>
    <%= form.text_field :url %>
  </div>

  <div class="field">
    <%= form.label :header_color %>
    <%= form.text_field :header_color %>
  </div>

  <div class="field">
    <%= form.label :header_text_color %>
    <%= form.text_field :header_text_color %>
  </div>

  <div class="field">
    <%= form.label :header_image %>
    <%= form.file_field :header_image %>
  </div>

  <div class="field">
    <%= form.label :header_cta_colour %>
    <%= form.text_field :header_cta_colour %>
  </div>

  <div class="field">
    <%= form.label :header_cta_text_color %>
    <%= form.text_field :header_cta_text_color %>
  </div>

  <div class="field">
    <%= form.label :country %>
    <%= form.text_field :country %>
  </div>

  <div class="field">
    <%= form.label :currency %>
    <%= form.text_field :currency %>
  </div>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/products/edit.html.erb
<h1>Editing Product</h1>

<%= render 'form', product: @product %>

<%= link_to 'Show', @product %> |
<%= link_to 'Back', products_path %>

app/views/products/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Products</h1>

<table>
  <thead>
    <tr>
      <th>Url</th>
      <th>Header color</th>
      <th>Header text color</th>
      <th>Header image</th>
      <th>Header cta colour</th>
      <th>Header cta text color</th>
      <th>Country</th>
      <th>Currency</th>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @products.each do |product| %>
      <tr>
        <td><%= product.url %></td>
        <td><%= product.header_color %></td>
        <td><%= product.header_text_color %></td>
        <td><%= product.header_image %></td>
        <td><%= product.header_cta_colour %></td>
        <td><%= product.header_cta_text_color %></td>
        <td><%= product.country %></td>
        <td><%= product.currency %></td>
        <td><%= product.name %></td>
        <td><%= link_to 'Show', product %></td>
        <td><%= link_to 'Edit', edit_product_path(product) %></td>
        <td><%= link_to 'Destroy', product, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Product', new_product_path %>

app/views/products/new.html.erb
<h1>New Product</h1>

<%= render 'form', product: @product %>

<%= link_to 'Back', products_path %>

app/views/products/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Url:</strong>
  <%= @product.url %>
</p>

<p>
  <strong>Header color:</strong>
  <%= @product.header_color %>
</p>

<p>
  <strong>Header text color:</strong>
  <%= @product.header_text_color %>
</p>

<p>
  <strong>Header image:</strong>
  <%= @product.header_image %>
</p>

<p>
  <strong>Header cta colour:</strong>
  <%= @product.header_cta_colour %>
</p>

<p>
  <strong>Header cta text color:</strong>
  <%= @product.header_cta_text_color %>
</p>

<p>
  <strong>Country:</strong>
  <%= @product.country %>
</p>

<p>
  <strong>Currency:</strong>
  <%= @product.currency %>
</p>

<p>
  <strong>Name:</strong>
  <%= @product.name %>
</p>

<%= link_to 'Edit', edit_product_path(@product) %> |
<%= link_to 'Back', products_path %>

app/views/products/view.html.erb
<style>
  #hero {
    background-color: #<%= @product.header_color %>;
    color: #<%= @product.header_text_color %>;    
  }
  .hero_cta {
    background-color: #<%= @product.header_cta_colour %>;
    color: #<%= @product.header_cta_text_color %>; 
    transition: all; 
    display: inline-block;
  }
  .hero_cta:hover {
    background-color: #1ED75F;
    color: #<%= @product.header_cta_text_color %>;   
    transform: scale(1.05);
  }  

  #lead {
    font-size: 3rem;
  }

  .sub2 {
    font-size: 1.5rem;
  }

  @media (min-width: 768px) {
    #lead {
      font-size: 5rem;
    }

    #hero {
      <% if @product.header_image.attached? %>
        background-image: url(<%= url_for(@product.header_image) %>);
      <% else %>
      <% end %>
    }

    .sub2 {
      font-size: 1.875rem;
    }    
  }
</style>

<div class="flex mb-4">
  <div id="hero" class="w-full min-h-64 pt-40 md:pt-32 px-5 md:px-16 bg-no-repeat bg-contain bg-right-bottom">
    <h1 id="lead" class="font-semibold "><%= @page.lead %></h1><br>
    <h2 class="sub2" class="font-medium"><%= @page.subtitle %></h2>
    <a class="hero_cta w-full md:w-auto text-center tracking-widest font-medium uppercase py-2 px-4 rounded-full px-12 py-3 my-10" href="https://www.spotify.com/purchase/offer/30day-intro-offer">
      <%= @page.cta_text %>
    </a> <br>
    <span class="font-light text-xs">*<%= link_to "Terms and conditions", terms_path, class: "underline" %> apply. <%= @page.sub_cta %></span><br><br>
  </div>
</div>
<br><br>

<div class="px-16 flex mb-4 justify-center">
  <h2 class="spotify-black font-semibold text-3xl md:text-5xl"><%= @page.benefits_header %></h2>
</div>
<br><br>
<div class="px-5 md:px-16 py-5 flex flex-wrap mb-4 md:justify-center">
  <%= render partial: "benefits", collection: @page.benefits %>
</div>
<br><br>
<div class="flex mb-4">
  <div class="w-0 md:w-1/4"></div>
  <div style="box-shadow: 0 0 7px #ded6d6;" class="w-full md:w-2/4 mx-5 bg-white rounded-lg px-6 p-3">
    <span class="text-2xl"><%= @page.product_name %></span><br>
    <span class="text-3xl font-semibold"><%= @product.currency %><%= @page.product_price %></span>&nbsp; / &nbsp;<%= @page.product_frequency %><br>
    <div class="text-xs text-gray-500 mb-2"><%= @page.product_info %><br></div>
    <hr>
    <br>
    <% for feature in @features %>
      <div class="my-2">
        <%= icon('fas', 'check') %> &nbsp; <%= feature %>
      </div>
    <% end %>
    <br>
    <hr>
    <a style="background-color: #1DB954; color: #fff;" class="hero_cta tracking-widest font-medium uppercase py-2 px-4 rounded-full px-12 py-3 my-2 w-full text-center" href="https://www.spotify.com/purchase/offer/30day-intro-offer">
      <%= @page.product_cta %>
    </a>  
  </div>
  <div class="w-0 md:w-1/4"></div>
</div>

<br><br>

<div class="flex mb-4">
  <div class="w-0 md:w-1/4"></div>
  <div style="box-shadow: 0 0 7px #ded6d6;" class="w-full md:w-2/4 mx-5 bg-white rounded-lg px-6 p-3">
    <div class="align-middle mx-5 flex flex-wrap my-5">
      <div class="inline-block align-middle text-2xl w-full md:w-2/3">Spotify Premium</div>
      <div style="color: #1ED75F;" class="inline-block mt-2 align-middle text-md w-full md:w-1/3 md:text-right tracking-widest font-medium uppercase">
        <%= link_to "Learn More", view_product_path("uk", "premium") %>
      </div>
    </div>
    <hr>  
    <div class="align-middle mx-5 flex flex-wrap my-5">
      <div class="inline-block align-middle text-2xl w-full md:w-2/3">Spotify Video</div>
      <div style="color: #1ED75F;" class="inline-block mt-2 align-middle text-md w-full md:w-1/3 md:text-right tracking-widest font-medium uppercase">
        <%= link_to "Learn More", view_product_path("uk", "video") %>
      </div>
    </div>
    <hr>
    <div class="align-middle mx-5 flex flex-wrap my-5">
      <div class="inline-block align-middle text-2xl w-full md:w-2/3">Spotify for Students</div>
      <div style="color: #1ED75F;" class="inline-block mt-2 align-middle text-md w-full md:w-1/3 md:text-right tracking-widest font-medium uppercase">
        <%= link_to "Learn More", view_product_path("uk", "students") %>
      </div>
    </div>
    <hr>
    <div class="align-middle mx-5 flex flex-wrap my-5">
      <div class="inline-block align-middle text-2xl w-full md:w-2/3">Homepage</div>
      <div style="color: #1ED75F;" class="inline-block mt-2 align-middle text-md w-full md:w-1/3 md:text-right tracking-widest font-medium uppercase">
        <%= link_to "Learn More", root_url %>
      </div>
    </div>            
  </div>
  <div class="w-0 md:w-1/4"></div>
</div>
<br><br>